version: '3'
services:
  filedrop:
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      - WS_HOST=0.0.0.0
      - WS_APP_NAME=${APP_NAME}
      - TURN_MODE=hmac
      - TURN_SERVER=turn:(hostname)
      - TURN_USERNAME=filedrop
      - TURN_SECRET=${TURN_SECRET}
      - VITE_APP_NAME=${APP_NAME}
      - VITE_APP_USE_BROWSER_ROUTER=1
    ports:
      - '${PORT}:5000'

  coturn:
    image: instrumentisto/coturn
    command: --use-auth-secret --static-auth-secret=${TURN_SECRET} --no-tls --no-dtls
    ports:
      - '3478:3478'
      - '49152-65535:49152-65535/udp'
